repos:
-   repo: local
    hooks:
    -   id: tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        types_or: [go, go-mod]
        pass_filenames: false
    -   id: test
        name: go test
        entry: go test ./...
        language: system
        types_or: [go, go-mod]
        pass_filenames: false
